"""init

Revision ID: 9f4326e504c4
Revises:
Create Date: 2026-05-21 22:56:11.048310

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f4326e504c4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('resource_model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='allocationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allocation_status', 'allocations', ['status'], unique=False)
    op.create_index('idx_allocation_subject', 'allocations', ['subject', 'created_at'], unique=False)
    op.create_table('call_records',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('allocation_id', sa.String(length=26), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.SmallInteger(), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'rejected_unauthenticated', 'rejected_revoked', 'rejected_model_mismatch', 'upstream_error', 'gateway_error', name='calloutcome', native_enum=False, length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_callrecord_allocation_time', 'call_records', ['allocation_id', 'started_at'], unique=False)
    op.create_index('idx_callrecord_outcome_time', 'call_records', ['outcome', 'started_at'], unique=False)
    op.create_table('credentials',
    sa.Column('allocation_id', sa.String(length=26), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id'),
    sa.UniqueConstraint('token_fingerprint')
    )
    op.create_index('idx_credential_fingerprint', 'credentials', ['token_fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_credential_fingerprint', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('idx_callrecord_outcome_time', table_name='call_records')
    op.drop_index('idx_callrecord_allocation_time', table_name='call_records')
    op.drop_table('call_records')
    op.drop_index('idx_allocation_subject', table_name='allocations')
    op.drop_index('idx_allocation_status', table_name='allocations')
    op.drop_table('allocations')
    # ### end Alembic commands ###
